# Generated by Django 4.1.2 on 2023-03-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('plate', models.TextField()),
                ('vehicleType', models.TextField()),
                ('document', models.TextField()),
                ('telephone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteNumber', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=1024)),
                ('hour', models.DateField()),
                ('quantity', models.TextField()),
                ('isConfirmedByHeritage', models.BooleanField(default=False)),
                ('isConfirmedByCPD', models.BooleanField(default=False)),
                ('isConfirmedByArbitrator', models.BooleanField(default=False)),
                ('loadType', models.TextField()),
                ('volumeType', models.TextField()),
                ('isChecked', models.BooleanField(default=False)),
                ('isReturned', models.BooleanField(default=False)),
                ('isSchedule', models.BooleanField(default=False)),
                ('idDriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('idNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notes')),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
    ]
