# Generated by Django 3.2 on 2023-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_provider_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='createAt',
            field=models.DateTimeField(null=True),
        ),
    ]
