# Generated by Django 3.2 on 2023-03-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provider_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
