# Generated by Django 3.2 on 2023-03-17 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230316_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='createAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
