# Generated by Django 3.2 on 2023-03-17 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_provider_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='createAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
